CC=g++#

CFLAGS=-c -WallLIBS=-lsfml-graphics -lsfml-window -lsfml-system  -lsfml-network

FILES=main.cpp Buff.cpp Bullet.cpp Enemy.cpp Entity.cpp Game.cpp HUD.cpp Level.cpp NetworkClient.cpp NetworkServer.cpp ObjectManager.cpp Player.cpp

TARGET=-o sfml-network-app
	all:	$(CC) $(FILES) $(TARGET) $(LIBS)
	clean:	rm -rf *.o all